# Generated by Django 5.2.13 on 2026-06-18 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.IntegerField(default=50)),
                ('energy', models.IntegerField(default=50)),
                ('growth', models.IntegerField(default=0)),
                ('fullness', models.IntegerField(default=50)),
                ('turn', models.IntegerField(default=1)),
                ('remaining_time', models.IntegerField(default=6)),
                ('play_count', models.IntegerField(default=0)),
                ('healthy_food_count', models.IntegerField(default=0)),
                ('snack_count', models.IntegerField(default=0)),
                ('character_state', models.CharField(default='normal', max_length=20)),
                ('room_wallpaper', models.CharField(default='room-default', max_length=50)),
                ('items', models.JSONField(default=list)),
                ('placed_items', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
